development:
  adapter: postgresql
  encoding: unicode
  database: ltk_development
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ltk_test
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_production
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password:
